settings:
  appDebug: true
  test: true
  database_mysql:
    #连接地址
    source: 'root:5eNyj6Nf@tcp(127.0.0.1:33060)/goweb?charset=utf8&parseTime=True&loc=Local&timeout=1000ms'
  redis:
    #redis连接地址
    root: '118.24.93.170'
    auth: 'zjllikeyjj'
    port: '6379'
    db: '0'
  proxy:
    #gin运行端口
    port: ':9086'